on:
  workflow_dispatch:
jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: npm install, build and test
        run: |
          npm install
          npm run build
          npm test
          
